title: M4luk0-Blog
description: "A small blog where I will upload some things I do like writeups and other in depth stuff."
author:
  name: "M4luk0"
  email: "jagilchamorro@gmail.com"
  url: "https://github.com/M4luk0"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
